library(fmtr)
library(readr)

fmt1 <- value(
  condition(x=='HK','HF'),
  condition(x=='VN','VS'),
  condition(x=='NB','NF'),
  condition(x=='HF','HB'),
  condition(x=='CK','CN'),
  condition(x=='VP','VB'),
  condition(x=='HO','HP'),
  condition(x=='NH','NN'),
  condition(x=='CC','CN'),
  condition(x=='FC','FP'),
  condition(x=='OK','OS'),
  condition(x=='OO','OP'),
  condition(x=='ON','OC'),
  condition(x=='VF','VB'),
  condition(x=='NN','NO'),
  condition(x=='KS','KP'),
  condition(x=='FK','FK'),
  condition(x=='HB','HV'),
  condition(x=='SH','SO'),
  condition(x=='OB','OK'),
  condition(x=='PB','PV'),
  condition(x=='BO','BO'),
  condition(x=='NV','NK'),
  condition(x=='CV','CH'),
  condition(x=='PH','PH'),
  condition(x=='KO','KB'),
  condition(x=='BC','BB'),
  condition(x=='KC','KB'),
  condition(x=='SO','SP'),
  condition(x=='CF','CV'),
  condition(x=='VS','VF'),
  condition(x=='OV','ON'),
  condition(x=='NS','NK'),
  condition(x=='KV','KO'),
  condition(x=='OP','OO'),
  condition(x=='HH','HC'),
  condition(x=='FB','FS'),
  condition(x=='CO','CK'),
  condition(x=='SB','SK'),
  condition(x=='SN','SV'),
  condition(x=='OF','OF'),
  condition(x=='BN','BF'),
  condition(x=='CP','CC'),
  condition(x=='NC','NH'),
  condition(x=='VH','VS'),
  condition(x=='HV','HV'),
  condition(x=='NF','NB'),
  condition(x=='SS','SK'),
  condition(x=='FO','FF'),
  condition(x=='VO','VH'),
  condition(x=='KK','KC'),
  condition(x=='PF','PV'),
  condition(x=='OS','OF'),
  condition(x=='OC','OH'),
  condition(x=='SK','SV'),
  condition(x=='FF','FH'),
  condition(x=='PK','PN'),
  condition(x=='PC','PO'),
  condition(x=='SP','SB'),
  condition(x=='CB','CB'),
  condition(x=='CH','CH'),
  condition(x=='FN','FV'),
  condition(x=='SV','SO'),
  condition(x=='SC','SP'),
  condition(x=='NP','NB'),
  condition(x=='BB','BS'),
  condition(x=='PV','PS'),
  condition(x=='VB','VP'),
  condition(x=='SF','SH'),
  condition(x=='VC','VO'),
  condition(x=='HN','HV'),
  condition(x=='BF','BO'),
  condition(x=='NO','NO'),
  condition(x=='HP','HN'),
  condition(x=='VV','VK'),
  condition(x=='HS','HP'),
  condition(x=='FH','FN'),
  condition(x=='KB','KF'),
  condition(x=='KF','KB'),
  condition(x=='PN','PK'),
  condition(x=='KH','KK'),
  condition(x=='CN','CS'),
  condition(x=='PP','PO'),
  condition(x=='BP','BO'),
  condition(x=='OH','OB'),
  condition(x=='FS','FO'),
  condition(x=='BK','BB'),
  condition(x=='PO','PV'),
  condition(x=='CS','CC'),
  condition(x=='BV','BN'),
  condition(x=='KP','KO'),
  condition(x=='KN','KB'),
  condition(x=='VK','VF'),
  condition(x=='HC','HO'),
  condition(x=='BH','BB'),
  condition(x=='FP','FH'),
  condition(x=='NK','NV'),
  condition(x=='BS','BC'),
  condition(x=='FV','FF'),
  condition(x=='PS','PP'))

fmt2 <- value(
  condition(x=='HK','FK'),
  condition(x=='VN','SN'),
  condition(x=='NB','FB'),
  condition(x=='HF','BF'),
  condition(x=='CK','NK'),
  condition(x=='VP','BP'),
  condition(x=='HO','PO'),
  condition(x=='NH','NH'),
  condition(x=='CC','NC'),
  condition(x=='FC','PC'),
  condition(x=='OK','SK'),
  condition(x=='OO','PO'),
  condition(x=='ON','CN'),
  condition(x=='VF','BF'),
  condition(x=='NN','ON'),
  condition(x=='KS','PS'),
  condition(x=='FK','KK'),
  condition(x=='HB','VB'),
  condition(x=='SH','OH'),
  condition(x=='OB','KB'),
  condition(x=='PB','VB'),
  condition(x=='BO','OO'),
  condition(x=='NV','KV'),
  condition(x=='CV','HV'),
  condition(x=='PH','HH'),
  condition(x=='KO','BO'),
  condition(x=='BC','BC'),
  condition(x=='KC','BC'),
  condition(x=='SO','PO'),
  condition(x=='CF','VF'),
  condition(x=='VS','FS'),
  condition(x=='OV','NV'),
  condition(x=='NS','KS'),
  condition(x=='KV','OV'),
  condition(x=='OP','OP'),
  condition(x=='HH','CH'),
  condition(x=='FB','SB'),
  condition(x=='CO','KO'),
  condition(x=='SB','KB'),
  condition(x=='SN','VN'),
  condition(x=='OF','FF'),
  condition(x=='BN','FN'),
  condition(x=='CP','CP'),
  condition(x=='NC','HC'),
  condition(x=='VH','SH'),
  condition(x=='HV','VV'),
  condition(x=='NF','BF'),
  condition(x=='SS','KS'),
  condition(x=='FO','FO'),
  condition(x=='VO','HO'),
  condition(x=='KK','CK'),
  condition(x=='PF','VF'),
  condition(x=='OS','FS'),
  condition(x=='OC','HC'),
  condition(x=='SK','VK'),
  condition(x=='FF','HF'),
  condition(x=='PK','NK'),
  condition(x=='PC','OC'),
  condition(x=='SP','BP'),
  condition(x=='CB','BB'),
  condition(x=='CH','HH'),
  condition(x=='FN','VN'),
  condition(x=='SV','OV'),
  condition(x=='SC','PC'),
  condition(x=='NP','BP'),
  condition(x=='BB','SB'),
  condition(x=='PV','SV'),
  condition(x=='VB','PB'),
  condition(x=='SF','HF'),
  condition(x=='VC','OC'),
  condition(x=='HN','VN'),
  condition(x=='BF','OF'),
  condition(x=='NO','OO'),
  condition(x=='HP','NP'),
  condition(x=='VV','KV'),
  condition(x=='HS','PS'),
  condition(x=='FH','NH'),
  condition(x=='KB','FB'),
  condition(x=='KF','BF'),
  condition(x=='PN','KN'),
  condition(x=='KH','KH'),
  condition(x=='CN','SN'),
  condition(x=='PP','OP'),
  condition(x=='BP','OP'),
  condition(x=='OH','BH'),
  condition(x=='FS','OS'),
  condition(x=='BK','BK'),
  condition(x=='PO','VO'),
  condition(x=='CS','CS'),
  condition(x=='BV','NV'),
  condition(x=='KP','OP'),
  condition(x=='KN','BN'),
  condition(x=='VK','FK'),
  condition(x=='HC','OC'),
  condition(x=='BH','BH'),
  condition(x=='FP','HP'),
  condition(x=='NK','VK'),
  condition(x=='BS','CS'),
  condition(x=='FV','FV'),
  condition(x=='PS','PS'))

orig_string <- "PHVCVBFHCVPFKBNHKNBO"
last_char <- str_sub(orig_string, -1)

new_tibble <- tibble(key = substring(orig_string, first = 1:(nchar(orig_string) - 1), last = 2:nchar(orig_string)))

for (j in 1:10) {
  new_tibble_h1 <- new_tibble %>%
    mutate(row_num = 2*row_number()-1) %>%
    mutate(result = fapply(key, fmt1))

  rm(new_tibble)

  new_tibble_h2 <- new_tibble_h1 %>%
    mutate(row_num = row_num +1) %>%
    mutate(result = fapply(key, fmt2))

  new_tibble <- full_join(new_tibble_h1, new_tibble_h2) %>%
    arrange(row_num) %>%
    select(result) %>%
    rename(key = result)

  rm(new_tibble_h1, new_tibble_h2)

  cat("End of loop j= ", j, "\n")
  new_tibble
}

final_list <- new_tibble %>%
  transmute(result = substr(key, 1, 1)) %>%
  pull(result)

final_list[length(final_list)+1] <- last_char

count_chars(final_list)

