# Fastest so far. :(

library(fmtr)
library(readr)

fmt1 <- value(
  condition(x=='HK','HF'),
  condition(x=='VN','VS'),
  condition(x=='NB','NF'),
  condition(x=='HF','HB'),
  condition(x=='CK','CN'),
  condition(x=='VP','VB'),
  condition(x=='HO','HP'),
  condition(x=='NH','NN'),
  condition(x=='CC','CN'),
  condition(x=='FC','FP'),
  condition(x=='OK','OS'),
  condition(x=='OO','OP'),
  condition(x=='ON','OC'),
  condition(x=='VF','VB'),
  condition(x=='NN','NO'),
  condition(x=='KS','KP'),
  condition(x=='FK','FK'),
  condition(x=='HB','HV'),
  condition(x=='SH','SO'),
  condition(x=='OB','OK'),
  condition(x=='PB','PV'),
  condition(x=='BO','BO'),
  condition(x=='NV','NK'),
  condition(x=='CV','CH'),
  condition(x=='PH','PH'),
  condition(x=='KO','KB'),
  condition(x=='BC','BB'),
  condition(x=='KC','KB'),
  condition(x=='SO','SP'),
  condition(x=='CF','CV'),
  condition(x=='VS','VF'),
  condition(x=='OV','ON'),
  condition(x=='NS','NK'),
  condition(x=='KV','KO'),
  condition(x=='OP','OO'),
  condition(x=='HH','HC'),
  condition(x=='FB','FS'),
  condition(x=='CO','CK'),
  condition(x=='SB','SK'),
  condition(x=='SN','SV'),
  condition(x=='OF','OF'),
  condition(x=='BN','BF'),
  condition(x=='CP','CC'),
  condition(x=='NC','NH'),
  condition(x=='VH','VS'),
  condition(x=='HV','HV'),
  condition(x=='NF','NB'),
  condition(x=='SS','SK'),
  condition(x=='FO','FF'),
  condition(x=='VO','VH'),
  condition(x=='KK','KC'),
  condition(x=='PF','PV'),
  condition(x=='OS','OF'),
  condition(x=='OC','OH'),
  condition(x=='SK','SV'),
  condition(x=='FF','FH'),
  condition(x=='PK','PN'),
  condition(x=='PC','PO'),
  condition(x=='SP','SB'),
  condition(x=='CB','CB'),
  condition(x=='CH','CH'),
  condition(x=='FN','FV'),
  condition(x=='SV','SO'),
  condition(x=='SC','SP'),
  condition(x=='NP','NB'),
  condition(x=='BB','BS'),
  condition(x=='PV','PS'),
  condition(x=='VB','VP'),
  condition(x=='SF','SH'),
  condition(x=='VC','VO'),
  condition(x=='HN','HV'),
  condition(x=='BF','BO'),
  condition(x=='NO','NO'),
  condition(x=='HP','HN'),
  condition(x=='VV','VK'),
  condition(x=='HS','HP'),
  condition(x=='FH','FN'),
  condition(x=='KB','KF'),
  condition(x=='KF','KB'),
  condition(x=='PN','PK'),
  condition(x=='KH','KK'),
  condition(x=='CN','CS'),
  condition(x=='PP','PO'),
  condition(x=='BP','BO'),
  condition(x=='OH','OB'),
  condition(x=='FS','FO'),
  condition(x=='BK','BB'),
  condition(x=='PO','PV'),
  condition(x=='CS','CC'),
  condition(x=='BV','BN'),
  condition(x=='KP','KO'),
  condition(x=='KN','KB'),
  condition(x=='VK','VF'),
  condition(x=='HC','HO'),
  condition(x=='BH','BB'),
  condition(x=='FP','FH'),
  condition(x=='NK','NV'),
  condition(x=='BS','BC'),
  condition(x=='FV','FF'),
  condition(x=='PS','PP'))

orig_string <- "PHVCVBFHCVPFKBNHKNBO"
last_char <- str_sub(orig_string, -1)

recent_string <- orig_string

for (j in 1:10) {
  new_list <- substring(recent_string, first = 1:(nchar(recent_string) - 1), last = 2:nchar(recent_string))
  recent_string <- str_c(paste(fapply(new_list, fmt1), collapse = ""), last_char)

  cat("End of loop j= ", j, "\n")
}

count_chars(recent_string)

